---
language: go
go:
  - "1.8"

branches:
  only:
  - main

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.81.0/hugo_extended_0.81.0_Linux-64bit.deb
  - sudo dpkg -i hugo_extended_0.81.0_Linux-64bit.deb
script:
  - git submodule update --init --recursive
  - hugo -D

after_script:
  - cd ./public
  - git init
  - git config user.name "Bitnut"
  - git config user.email "940095072@qq.com"
  - git add .
  - git commit -m "Update Blog By TravisCI With Build $TRAVIS_BUILD_NUMBER"
  # Github Pages
  - git push --force --quiet "https://$GITHUB_TOKEN@${GH_REF}" master:master --tags

env:
 global:
   # Github Pages
   - GH_REF: github.com/Bitnut/Bitnut.github.io.git

deploy:
  provider: pages
  skip_cleanup: true
  local-dir: public
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: main