title = "三口一个瓜的博客"
baseURL = "https://bitnut.github.io"
languageCode = "en-us"
theme = "researcher"

disableKinds = ["taxonomy", "term"]
enableEmoji = true
math = false          # enable KaTeX (https://katex.org/) globally
googleAnalytics = ""  # add your tracking id

[params]
  author = "三口一个瓜"
  description = "A simple monospaced resume theme for Hugo."
  favicon = "favicon.ico"  # path to a .ico to use as favicon
  logo = ""  # url or path to a logo to put in the header
  [params.footer]
    text = "By 三口一个瓜"
    url = "https://github.com/Bitnut"
  [params.style]  # appearance options (can be omitted)
    fontFamily = "Inconsolata"
    pageWidth = "750px"
    avatarSize = "90px"
    colorBlack = "#222222"
    colorRed = "#dc3545"

[permalinks]
  "/" = "/:filename"

[menu]
  [[menu.main]]
    name = "博客"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "关于我"
    url = "/abo"
    weight = 2
  [[menu.main]]
    name = "联系方式"
    url = "/contact"
    weight = 3



[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files